---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: interval
      time: "07:30"
    open-pull-requests-limit: 1
    reviewers:
      - bbarwik
