name: Windows Debug Build
on: [workflow_dispatch]

jobs:
  Windows:
    name: Build windows version
    runs-on: windows-2019
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        id: setup_msbuild

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgTriplet: x86-windows-static
          vcpkgGitCommitId: 3b3bd424827a1f7f4813216f6b32b6c61e386b2e
          vcpkgArguments: >
            boost-iostreams boost-asio boost-beast boost-system boost-variant boost-lockfree boost-process boost-program-options boost-uuid boost-filesystem
            luajit glew physfs openal-soft libogg libvorbis zlib libzip bzip2 openssl liblzma

      - name: Integrate vcpkg
        run: |
          ${{ runner.workspace }}\vcpkg\vcpkg integrate install

      - name: Compile
        timeout-minutes: 60
        run: |
          cd vc16
          MSBuild /property:Configuration=Debug_lib /p:BUILD_REVISION=${{github.run_number}}
          MSBuild /property:Configuration=Debug /p:BUILD_REVISION=${{github.run_number}}
